server:
  port: 8001

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysqlnotest

#可以考虑换成mybatisPlus或jpa
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.mdemo.springcloud.entities